---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-app-jwt2token-controller
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-app-jwt2token-controller
  namespace: default
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "update", "create", "delete"]
- apiGroups: ["githubapp.technicaldomain.xyz"]
  resources: ["argocdrepos", "dockerconfigjsons"]
  verbs: ["get", "list", "watch", "update", "patch", "create", "delete"]
- apiGroups: ["githubapp.technicaldomain.xyz"]
  resources: ["argocdrepos/status", "dockerconfigjsons/status"]
  verbs: ["update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-app-jwt2token-controller
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: github-app-jwt2token-controller
subjects:
- kind: ServiceAccount
  name: github-app-jwt2token-controller
  namespace: default
